device: "cuda:0"

data:
  class_path: 'dataset.tomato_dataset.TomatoDataset'
  base_path: "dataset/data/tomato"
  img_height: 224
  img_width: 224
  n_channels: 3
  num_classes: 10

model:
  type: 'vit'
  patch_size: 6
  latent_size: 480
  num_heads: 12
  num_encoders: 6
  dropout: 0.1

  #type: 'resnet'
  #num_blocks: [4, 8]
  #block_channels: 64
  #dropout: 0.1

model_checkpoint:
  base_path: './experiments'
  save_freq: 1

training:
  epochs: 20
  lr: 0.001
  weight_decay: 0.0
  batch_size: 4

logger:
  base_path: './experiments'
  step: 100
  max_grid_dim: 16